

spring.datasource.url=jdbc:mysql://localhost:3306/LeaveApplication 
spring.datasource.username=root
spring.datasource.password=root
#spring.datasource.password=200318

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#jwt spring security configuration
jwt.secret=bXlTdXBlclNlY3VyZUp3dFNlY3JldEtleUZvckVMTVNQcm9qZWN0

#1 day token expiration
jwt.expiration=86400000	
